"""add supabase + stripe columns to users

Revision ID: 305b3b313e2f
Revises: 4388573a2270
Create Date: 2026-02-22 16:49:43.004217
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '305b3b313e2f'
down_revision: Union[str, None] = '4388573a2270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
